[bot]
name = "Nametags Discord Bot"
version = "1.0.0"

[logging]
base_level = "INFO"
file = "logs/bot.log"
rotate_daily = true
backup_count = 50
disable_file_logging = false
disable_console_logging = false
