[bot]
name = "Nametags Discord Bot"
version = "1.0.1"
bio_placeholder = """
Likes, dislikes, hobbies, etc.
"""

[logging]
base_level = "INFO"
logfile_backup_count = 50
disable_file_logging = false
disable_console_logging = false
